version: '3.4'

services:
  frontend:
    image: ggchallenge
    restart: always
    container_name: gg
    environment:
      FLASK_APP: ${F_APP}
      FLASK_ENV: ${F_ENV}
    ports:
      - 8080:8080
